# Generated by Django 4.2.7 on 2023-12-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubatordevice',
            name='last_completion_data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
